server:
  port: 8081

spring:
  application:
    name: articles
  datasource:
    username: 's4you'
    url: jdbc:postgresql://localhost:5432/articles
    password: 'admin'
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        hbm2ddl.auto: create-drop
    show-sql: true